### ISSUE TITLE
Bug in testing asynchronous routines

### ISSUE THREAD

**Issue by xixiaofinland** [surajp/universalmock#16]
My production code goes as - `sut` invokes `dataService.importPortals()` inside.
The test fails with `Expected: 1, Actual: 0`

However, `System.debug` tells the mocked Integer (100) is corrected returned by the `importPortals` method.

What do I miss?

```
        String methodName = 'importPortals';
        mockDataService.when(methodName).thenReturn(100);

        Test.startTest();
        System.enqueueJob(sut);
        Test.stopTest();

        mockDataService.assertThat().method(methodName).wasCalled(1);
```

**Comment by surajp** [comment]
Are you injecting the stub into your queueable job somewhere? I am not seeing it here

**Comment by surajp** [comment]
@xixiaofinland I ran some more tests and looks like this is a bug with the library. Since the dependency that is used within an async job is a copy of the original dependency, the call counts are not updated in the state of the original universalmocker instance. I usually test my async code by calling the `execute` method directly and completely overlooked this. I will convert this to a bug and release a fix soon. Thanks for raising the issue.

**Comment by surajp** [comment]
@xixiaofinland if you want to take a look at #17 it addresses the issue with async contexts

**Comment by xixiaofinland** [comment]
> #17

Thanks for the tip, all clear now
